version: '2'
services:
  kafka1:
    build: ./kafka
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 52.208.31.248
      ADVERTISED_PORT: 9092
      ZOOKEEPER_CONNECT: zoo1:2181

  kafka2:
    build: ./kafka
    depends_on:
      - zoo1
    ports:
      - "9093:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 52.208.31.248
      ADVERTISED_PORT: 9093
      ZOOKEEPER_CONNECT: zoo1:2181

  kafka3:
    build: ./kafka
    depends_on:
      - zoo1
    ports:
      - "9094:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 52.208.31.248
      ADVERTISED_PORT: 9094
      ZOOKEEPER_CONNECT: zoo1:2181

  zoo1:
    build: ./zookeeper
    environment:
      SERVERS: 52.208.31.248
    ports:
      - "2181:2181"

