version: '2'
services:
  kafka1:
    image: omarewedah/kafka
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      ADVERTISED_PORT: 9092
      ZOOKEEPER_CONNECT: zoo1:2181

  kafka2:
    image: omarewedah/kafka
    depends_on:
      - zoo1
    ports:
      - "9093:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      ADVERTISED_PORT: 9093
      ZOOKEEPER_CONNECT: zoo1:2181

  kafka3:
    image: omarewedah/kafka
    depends_on:
      - zoo1
    ports:
      - "9094:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      ADVERTISED_PORT: 9094
      ZOOKEEPER_CONNECT: zoo1:2181

  zoo1:
    image: omarewedah/zookeeper
    ports:
      - "2181:2181"

